name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install Protoc
      run: |
        sudo apt install -y protobuf-compiler
        protoc --version

    - name: Install Protoc-gen-go
      run: |
        make dev-deps

    - name: Build
      run: make build

    - name: Audit
      run: make audit
